export default {
  appName: 'MyNAS', secureName: 'MyNAS Secure', personalCloud: 'PERSONAL CLOUD',
  nav: { dashboard: 'Overview', photos: 'Photos', timeline: 'Timeline', recent: 'Recent', videos: 'Videos', documents: 'Documents', downloads: 'Downloads', backup: 'Backup', trash: 'Trash', security: 'Security', settings: 'Settings' },
  common: { save: 'Save', cancel: 'Cancel', add: 'Add', edit: 'Edit', delete: 'Delete', default: 'Default', setDefault: 'Set default', refresh: 'Refresh', loading: 'Loading…', never: 'Never', available: 'Available', unavailable: 'Unavailable', logout: 'Sign out', close: 'Close', confirm: 'Confirm', success: 'Done', failed: 'Failed' },
  auth: { title: 'Sign in to your private cloud', subtitle: 'Your files, photos, and backups are protected by account isolation and audit logs.', username: 'Username', password: 'Password', login: 'Secure sign in', loggingIn: 'Signing in…', firstLogin: 'First sign-in: admin / admin', changeDefaultTitle: 'Change the default password', changeDefaultText: 'Set a new password before accessing your private files.', currentPassword: 'Current password', newPassword: 'New password', confirmPassword: 'Confirm new password', setPassword: 'Set password and continue', saving: 'Saving…', mismatch: 'The new passwords do not match', loginFailed: 'Sign-in failed', passwordChanged: 'Password changed' },
  dashboard: { welcome: 'Welcome back', subtitle: 'Your personal storage, fully under your control.', secure: 'SECURE DATA', heroTitle: 'Your digital life, safely kept here.', heroText: 'Photos, videos, and important files stay on your own Windows PC.', upload: 'Upload files', used: 'Used', storage: 'Storage', remaining: 'Free', overview: 'Space overview', recentPhotos: 'Recent uploads', recentActivity: 'Recent activity', activityHint: 'File changes and actions', backupStatus: 'Backup status', systemHealth: 'System health', healthy: 'Healthy', photos: 'Photos', videos: 'Videos', files: 'Files', favorites: 'Favorites', noActivity: 'No activity yet', openAlbum: 'Open photos' },
  photos: { album: 'Photos', albumSubtitle: '{count} photos arranged by capture time.', timelineSubtitle: 'Capture time first, grouped by year / month / day.', recentSubtitle: 'Photos recently added to MyNAS.', all: 'All Photos', timeline: 'Timeline', recent: 'Recent', today: 'Today', sevenDays: 'Last 7 days', upload: 'Upload photos', arranging: 'Organizing photos…', empty: 'No photos yet', emptyText: 'Upload a JPEG or PNG and MyNAS will create thumbnails and read capture time.', uploadFirst: 'Upload your first photo', count: '{count} photos', favorite: 'Favorite', unfavorite: 'Remove favorite', loadMore: 'Load more photos', loadingMore: 'Loading…', filter: 'Filter current photos', previous: 'Previous (←)', next: 'Next (→)', closeEsc: 'Close (Esc)', selected: '{count} selected', select: 'Select', done: 'Done', batchDelete: 'Delete', batchDownload: 'Download', batchFavorite: 'Favorite', jumpYear: 'Jump by year', jumpMonth: 'Jump by month', deleteConfirm: 'Delete the selected photos?' },
  files: { title: 'Files', search: 'Search files', newFolder: 'New folder', upload: 'Upload', name: 'Name', size: 'Size', modified: 'Modified', reading: 'Reading files…', empty: 'Nothing here yet', emptyText: 'Upload files or create a folder to begin.', uploadFile: 'Upload file', folderName: 'Folder name', createFolder: 'Create folder', createText: 'Create a new folder in this location.', deleteConfirm: 'Move “{name}” to Trash?', permanentConfirm: 'Permanently delete “{name}”? This cannot be undone.' },
  upload: { title: 'Upload to {target}', safeText: 'Files are stored under secure random UUIDs. Disk paths are never exposed.', choose: 'Choose JPEG, PNG, MP4, or PDF', chosen: '{count} files selected', blocked: 'Scripts and executables are blocked', start: 'Start upload', drop: 'Drop files here, or click to browse', complete: '{count} files uploaded', failed: 'Upload failed: {reason}' },
  trash: { title: 'Trash', empty: 'Trash is empty', emptyText: 'Deleted files are kept here temporarily.', clear: 'Empty Trash', clearConfirm: 'Empty Trash permanently?', restore: 'Restore', permanent: 'Delete permanently' },
  settings: { title: 'Settings', subtitle: 'Manage your account, storage, backup, and product preferences.', account: 'Account', accountText: 'Current session and security actions', username: 'Username', role: 'Role', administrator: 'Administrator', session: 'Session', issuedAt: 'Issued', expiresAt: 'Expires', authType: 'Authentication', changeUsername: 'Change username', changePassword: 'Change password', language: 'Language', languageText: 'Your language remains selected after refresh', chinese: '简体中文', english: 'English', storage: 'Storage', storageText: 'Manage Windows storage locations', storageName: 'Storage name', storagePath: 'Windows path', addStorage: 'Add storage', editStorage: 'Edit storage', capacity: 'Capacity', free: 'Free', backup: 'Backup', backupText: 'Manage incremental backup destination and daily schedule', backupDirectory: 'Backup directory', autoBackup: 'Automatic backup', dailyTime: 'Daily run time', runNow: 'Back up now', lastBackup: 'Last backup', system: 'System', systemText: 'MyNAS runtime and data statistics', preferences: 'System preferences', preferencesText: 'Adjust appearance and default behavior', theme: 'Theme', light: 'Light', darkReserved: 'Dark (reserved)', defaultHome: 'Default home', defaultUpload: 'Default upload folder', photoSort: 'Photo sorting', newestTaken: 'Capture time: newest first', oldestTaken: 'Capture time: oldest first', newestUploaded: 'Upload time: newest first', python: 'Python Version', sqlite: 'SQLite Version', version: 'MyNAS Version', databaseSize: 'Database Size', thumbnailSize: 'Thumbnail Cache Size', assetCount: 'Asset Count', photoCount: 'Photo Count', storageUsage: 'Storage Usage', saved: 'Settings saved' },
  errors: { unauthorized: 'Your session expired. Sign in again.', forbidden: 'You do not have permission for this action.', notFound: 'The requested resource was not found.', conflict: 'That name or path already exists.', validation: 'Please check the entered values.', network: 'Cannot connect to MyNAS.', generic: 'Something went wrong. Please try again.' }
}
