export default {
  appName: 'MyNAS', secureName: 'MyNAS Secure', personalCloud: '个人云存储',
  nav: { dashboard: '总览', photos: '相册', timeline: '时间轴', recent: '最近上传', videos: '视频', documents: '文档', downloads: '下载', backup: '备份', trash: '回收站', security: '安全中心', settings: '设置' },
  common: { save: '保存', cancel: '取消', add: '新增', edit: '编辑', delete: '删除', default: '默认', setDefault: '设为默认', refresh: '刷新', loading: '正在加载…', never: '从未', available: '可用', unavailable: '不可用', logout: '退出登录', close: '关闭', confirm: '确认', success: '操作成功', failed: '操作失败' },
  auth: { title: '登录私人云空间', subtitle: '所有文件、照片和备份均受账号隔离与操作审计保护。', username: '用户名', password: '密码', login: '安全登录', loggingIn: '正在登录…', firstLogin: '首次登录账号：admin，初始密码：admin', changeDefaultTitle: '请先修改默认密码', changeDefaultText: '为了保护你的私有文件，首次登录后必须设置一个新密码，完成前其他功能保持锁定。', currentPassword: '当前密码', newPassword: '新密码', confirmPassword: '确认新密码', setPassword: '设置新密码并继续', saving: '正在保存…', mismatch: '两次输入的新密码不一致', loginFailed: '登录失败', passwordChanged: '密码修改成功' },
  dashboard: { welcome: '欢迎回来', subtitle: '这是你的个人存储空间，一切都由你掌控。', secure: '数据安全', heroTitle: '你的数字生活，妥善存放在这里。', heroText: '照片、视频与重要文件都保存在你自己的 Windows 电脑上。', upload: '上传文件', used: '已使用', storage: '存储空间', remaining: '剩余', overview: '空间概览', recentPhotos: '最近上传照片', recentActivity: '最近活动', activityHint: '文件变更记录', backupStatus: '备份状态', systemHealth: '系统健康', healthy: '运行正常', photos: '照片', videos: '视频', files: '文件', favorites: '收藏', noActivity: '还没有活动记录', openAlbum: '打开相册' },
  photos: { album: '相册', albumSubtitle: '{count} 张照片，按拍摄时间自然排列。', timelineSubtitle: '优先使用照片拍摄时间，按年 / 月 / 日回看。', recentSubtitle: '最近进入 MyNAS 的照片。', all: '所有照片', timeline: '时间轴', recent: '最近上传', today: '今天', sevenDays: '最近 7 天', upload: '上传照片', arranging: '正在整理照片…', empty: '还没有照片', emptyText: '上传 JPEG 或 PNG，MyNAS 会自动生成缩略图并读取拍摄时间。', uploadFirst: '上传第一张照片', count: '{count} 张', favorite: '收藏', unfavorite: '取消收藏', loadMore: '加载更多照片', loadingMore: '正在加载…', filter: '筛选当前照片', previous: '上一张（←）', next: '下一张（→）', closeEsc: '关闭（Esc）', selected: '已选择 {count} 张', select: '选择', done: '完成', batchDelete: '批量删除', batchDownload: '批量下载', batchFavorite: '批量收藏', jumpYear: '按年份', jumpMonth: '按月份', deleteConfirm: '确定删除选中的照片吗？' },
  files: { title: '文件', search: '搜索文件', newFolder: '新建文件夹', upload: '上传', name: '名称', size: '大小', modified: '修改时间', reading: '正在读取文件…', empty: '这里还是空的', emptyText: '上传文件或新建文件夹，开始建立你的个人空间。', uploadFile: '上传文件', folderName: '文件夹名称', createFolder: '创建文件夹', createText: '在当前目录创建一个新的文件夹。', deleteConfirm: '确定将“{name}”移到回收站吗？', permanentConfirm: '永久删除“{name}”吗？此操作无法撤销。' },
  upload: { title: '上传到 {target}', safeText: '文件将以随机 UUID 安全存储，原始磁盘路径不会暴露。', choose: '选择 JPEG、PNG、MP4 或 PDF', chosen: '已选择 {count} 个文件', blocked: '禁止脚本和可执行文件', start: '开始上传', drop: '拖拽文件到这里，或点击选择', complete: '已成功上传 {count} 个文件', failed: '上传失败：{reason}' },
  trash: { title: '回收站', empty: '回收站是空的', emptyText: '删除的文件会暂时保存在这里。', clear: '清空回收站', clearConfirm: '确定清空回收站吗？此操作无法撤销。', restore: '恢复', permanent: '永久删除' },
  settings: { title: '设置', subtitle: '管理你的账户、存储、备份和产品偏好。', account: '账户', accountText: '当前登录信息与安全操作', username: '用户名', role: '角色', administrator: '管理员', session: 'Session 信息', issuedAt: '登录时间', expiresAt: '过期时间', authType: '认证方式', changeUsername: '修改用户名', changePassword: '修改密码', language: '语言', languageText: '界面语言会在刷新后保持', chinese: '简体中文', english: 'English', storage: '存储', storageText: '管理可用的 Windows 存储位置', storageName: '存储名称', storagePath: 'Windows 路径', addStorage: '新增 Storage', editStorage: '修改 Storage', capacity: '容量', free: '剩余', backup: '备份', backupText: '管理增量备份目录与每日计划', backupDirectory: '备份目录', autoBackup: '自动备份', dailyTime: '每天执行时间', runNow: '立即备份', lastBackup: '最近一次备份', system: '系统', systemText: 'MyNAS 运行环境与数据统计', preferences: '系统设置', preferencesText: '调整外观和默认行为', theme: '主题', light: '浅色模式', darkReserved: '深色模式（预留）', defaultHome: '默认首页', defaultUpload: '默认上传目录', photoSort: '照片排序', newestTaken: '拍摄时间：最新优先', oldestTaken: '拍摄时间：最早优先', newestUploaded: '上传时间：最新优先', python: 'Python Version', sqlite: 'SQLite Version', version: 'MyNAS Version', databaseSize: 'Database Size', thumbnailSize: 'Thumbnail Cache Size', assetCount: 'Asset Count', photoCount: 'Photo Count', storageUsage: 'Storage Usage', saved: '设置已保存' },
  errors: { unauthorized: '登录已失效，请重新登录', forbidden: '没有权限执行此操作', notFound: '请求的资源不存在', conflict: '名称或路径已存在', validation: '输入内容不符合要求', network: '无法连接 MyNAS 服务', generic: '操作失败，请稍后重试' }
}
